# Generated by Django 5.1.2 on 2024-12-19 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_productreview_image_productreviewimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreviewimage',
            options={'verbose_name': 'Картинка к отзывам на товары', 'verbose_name_plural': 'Картинки к отзывам на товары'},
        ),
    ]
