# Generated by Django 5.1.2 on 2024-12-19 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_productreviewimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='images',
            field=models.ManyToManyField(blank=True, to='api.productreviewimage'),
        ),
        migrations.AlterField(
            model_name='productreviewimage',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_images', to='api.productreview'),
        ),
    ]
