# Generated by Django 5.1.2 on 2024-12-19 19:40

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_productreview_images_alter_productreviewimage_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='images',
        ),
        migrations.AddField(
            model_name='productreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.product_review_image_path),
        ),
        migrations.DeleteModel(
            name='ProductReviewImage',
        ),
    ]
