# Generated by Django 5.1.2 on 2024-12-20 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_reviewimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='image',
        ),
    ]
