# Generated by Django 5.1.2 on 2024-12-20 12:51

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_productreview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.product_review_image_path),
        ),
        migrations.DeleteModel(
            name='ReviewImage',
        ),
    ]
