# Generated by Django 5.1.2 on 2024-12-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_category_description_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
