# Generated by Django 5.1.2 on 2025-01-15 12:38

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_productreview_cons_productreview_pros'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.profile_pic_image_path, verbose_name='Фото профиля'),
        ),
    ]
